"""create jobs table

Revision ID: 95470bb2dcf0
Revises: 0001
Create Date: 2026-08-07 16:15:36.972224

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95470bb2dcf0"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("company", sa.String(length=255), nullable=False),
        sa.Column("company_url", sa.String(length=500), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column(
            "remote_type",
            sa.Enum(
                "remote",
                "hybrid",
                "onsite",
                "unknown",
                name="remotetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "employment_type",
            sa.Enum(
                "full_time",
                "part_time",
                "contract",
                "internship",
                "freelance",
                name="employmenttype",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "experience_level",
            sa.Enum(
                "intern",
                "junior",
                "mid",
                "senior",
                "staff",
                "lead",
                "unknown",
                name="experiencelevel",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=True),
        sa.Column("description_raw", sa.Text(), nullable=True),
        sa.Column("description_structured", sa.JSON(), nullable=True),
        sa.Column("application_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "source_platform",
            sa.Enum(
                "linkedin",
                "greenhouse",
                "lever",
                "wellfound",
                "yc",
                "company_site",
                "other",
                name="sourceplatform",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("external_job_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "matched",
                "shortlisted",
                "applied",
                "interview",
                "offer",
                "rejected",
                "archived",
                name="jobstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "embedding_generated", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("applied", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "match_score IS NULL OR (match_score >= 0 AND match_score <= 1)",
            name=op.f("ck_jobs_match_score"),
        ),
        sa.CheckConstraint(
            "salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max",
            name=op.f("ck_jobs_salary_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint(
            "source_platform",
            "external_job_id",
            name="uq_jobs_source_platform_external_job_id",
        ),
    )
    op.create_index(op.f("ix_jobs_company"), "jobs", ["company"], unique=False)
    op.create_index("ix_jobs_company_title", "jobs", ["company", "title"], unique=False)
    op.create_index(
        op.f("ix_jobs_discovered_at"), "jobs", ["discovered_at"], unique=False
    )
    op.create_index(op.f("ix_jobs_location"), "jobs", ["location"], unique=False)
    op.create_index(op.f("ix_jobs_posted_at"), "jobs", ["posted_at"], unique=False)
    op.create_index(
        op.f("ix_jobs_source_platform"), "jobs", ["source_platform"], unique=False
    )
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(
        "ix_jobs_status_discovered_at",
        "jobs",
        ["status", "discovered_at"],
        unique=False,
    )
    op.create_index(op.f("ix_jobs_title"), "jobs", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_title"), table_name="jobs")
    op.drop_index("ix_jobs_status_discovered_at", table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_source_platform"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_posted_at"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_location"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_discovered_at"), table_name="jobs")
    op.drop_index("ix_jobs_company_title", table_name="jobs")
    op.drop_index(op.f("ix_jobs_company"), table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
